{% set name = "covtrim" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .


channels:
  - gosahan
  - fastchan
  - conda-forge
  - bioconda
  - defaults

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv || bash post-build.sh" 

requirements:
  host:
    - python <3.11
    - pip
    - setuptools
    - wheel
    - poetry-core
  run:
    - python <3.11
    - numpy
    - pandas
    - pysam
    - scipy

test:
  imports:
    - numpy
    - pandas
    - pysam
    - scipy
  commands:
    - python -V
    - covtrim --version
    - covtrim --help

about:
  home: https://github.com/phac-nml/covtrim
  summary: Coverage-based FASTQ downsampling tool for amplicon sequencing data
  description: |
    CovTrim is a specialized bioinformatics tool designed for precise 
    coverage-based downsampling of FASTQ files from amplicon sequencing data.
    It intelligently adjusts sequencing depth while maintaining quality metrics 
    and amplicon representation.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/phac-nml/covtrim/blob/main/README.md
  dev_url: https://github.com/phac-nml/covtrim

extra:
  recipe-maintainers:
    - gosahan
  keywords:
    - bioinformatics
    - genomics
    - NGS
    - amplicon
    - coverage
    - fastq
    - sequencing